"""move column to another table

Revision ID: 9ece49edc3eb
Revises: 19c09ff57dec
Create Date: 2024-11-06 14:15:27.685313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ece49edc3eb'
down_revision: Union[str, None] = '19c09ff57dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alternatives', 'alternative_values')
    op.add_column('criteria', sa.Column('alternatives_values', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'alternatives_values')
    op.add_column('alternatives', sa.Column('alternative_values', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
