"""change alternatives column

Revision ID: 19c09ff57dec
Revises: 
Create Date: 2024-11-01 14:59:58.430313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19c09ff57dec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternatives', sa.Column('alternative_values', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('alternatives', 'alternative_obj')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternatives', sa.Column('alternative_obj', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('alternatives', 'alternative_values')
    # ### end Alembic commands ###
