"""add tradeoffs table; fix relationships

Revision ID: d5b125662115
Revises: 9ece49edc3eb
Create Date: 2024-11-16 16:15:15.982589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5b125662115'
down_revision: Union[str, None] = '9ece49edc3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_offs',
    sa.Column('trade_off_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria_weights', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('decision_method', sa.String(length=80), nullable=True),
    sa.Column('normalization_method', sa.String(length=80), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='Cascade'),
    sa.PrimaryKeyConstraint('trade_off_id')
    )
    op.create_index(op.f('ix_trade_offs_task_id'), 'trade_offs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_offs_task_id'), table_name='trade_offs')
    op.drop_table('trade_offs')
    # ### end Alembic commands ###
